export const epData = [
  {
    id: 124,
    name: '"Zero Larp Thirty"',
    productionCode: '7ASA01',
    airDate: 'April 23, 2017',
    season: 7,
    episode: 17,
    totalViewers: '1.579 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/124',
  },
  {
    id: 187,
    name: '"Yurty Rotten Scoundrels"',
    productionCode: '9ASA16',
    airDate: 'March 8, 2020',
    season: 10,
    episode: 15,
    totalViewers: '1.279 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/187',
  },
  {
    id: 171,
    name: '"Yes Without My Zeke"',
    productionCode: '8ASA26',
    airDate: 'May 12, 2019',
    season: 9,
    episode: 22,
    totalViewers: '1.484 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/171',
  },
  {
    id: 203,
    name: '"Yachty or Nice"',
    productionCode: 'AASA09',
    airDate: 'December 13, 2020',
    season: 11,
    episode: 10,
    totalViewers: '1.808 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/203',
  },
  {
    id: 209,
    name: '"Y Tu Tina También',
    productionCode: 'AASA15',
    airDate: 'March 28, 2021',
    season: 11,
    episode: 16,
    totalViewers: '1.068 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/209',
  },
  {
    id: 135,
    name: '"Y Tu Ga-Ga Tambien"',
    productionCode: '7ASA12',
    airDate: 'March 11, 2018',
    season: 8,
    episode: 9,
    totalViewers: '1.837 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/135',
  },
  {
    id: 194,
    name: '"Worms of In-Rear-ment"',
    productionCode: '9ASA23',
    airDate: 'October 4, 2020',
    season: 11,
    episode: 2,
    totalViewers: '1.123 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/194',
  },
  {
    id: 67,
    name: '"World Wharf II: The Wharfening"',
    productionCode: '4ASA10',
    airDate: 'May 18, 2014',
    season: 4,
    episode: 22,
    totalViewers: '1.954 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/67',
  },
  {
    id: 71,
    name: '"Work Hard or Die Trying, Girl"',
    productionCode: '4ASA14',
    airDate: 'October 5, 2014',
    season: 5,
    episode: 1,
    totalViewers: '3.140 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/71',
  },
  {
    id: 166,
    name: '"What About Blob?"',
    productionCode: '8ASA21',
    airDate: 'March 17, 2019',
    season: 9,
    episode: 17,
    totalViewers: '2.082 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/166',
  },
  {
    id: 66,
    name: '"Wharf Horse"',
    productionCode: '4ASA09',
    airDate: 'May 11, 2014',
    season: 4,
    episode: 21,
    totalViewers: '1.972 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/66',
  },
  {
    id: 11,
    name: '"Weekend at Mort\'s"',
    productionCode: '1ASA11',
    airDate: 'May 8, 2011',
    season: 1,
    episode: 11,
    totalViewers: '4.26 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/11',
  },
  {
    id: 185,
    name: '"Wag the Song"',
    productionCode: '9ASA14',
    airDate: 'March 1, 2020',
    season: 10,
    episode: 14,
    totalViewers: '1.432 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/185',
  },
  {
    id: 101,
    name: '"Wag the Hog"',
    productionCode: '5ASA22',
    airDate: 'April 10, 2016',
    season: 6,
    episode: 13,
    totalViewers: '2.348 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/101',
  },
  {
    id: 212,
    name: '"Vampire Disco Death Dance"',
    productionCode: 'AASA18',
    airDate: 'May 23, 2021',
    season: 11,
    episode: 22,
    totalViewers: '0.975 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/212',
  },
  {
    id: 144,
    name: '"V for Valentine-detta"',
    productionCode: '7ASA22',
    airDate: 'January 14, 2018',
    season: 8,
    episode: 8,
    totalViewers: '4.757 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/144',
  },
  {
    id: 57,
    name: '"Uncle Teddy"',
    productionCode: '3ASA22',
    airDate: 'March 23, 2014',
    season: 4,
    episode: 14,
    totalViewers: '2.450 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/57',
  },
  {
    id: 159,
    name: '"UFO No You Didn\'t"',
    productionCode: '8ASA14',
    airDate: 'December 2, 2018',
    season: 9,
    episode: 9,
    totalViewers: '2.994 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/159',
  },
  {
    id: 39,
    name: '"Two for Tina"',
    productionCode: '3ASA04',
    airDate: 'March 17, 2013',
    season: 3,
    episode: 17,
    totalViewers: '3.62 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/39',
  },
  {
    id: 154,
    name: '"Tweentrepreneurs"',
    productionCode: '8ASA09',
    airDate: 'October 14, 2018',
    season: 9,
    episode: 3,
    totalViewers: '2.136 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/154',
  },
  {
    id: 51,
    name: '"Turkey in a Can"',
    productionCode: '3ASA16',
    airDate: 'November 24, 2013',
    season: 4,
    episode: 5,
    totalViewers: '4.076 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/51',
  },
  {
    id: 12,
    name: '"Torpedo"',
    productionCode: '1ASA12',
    airDate: 'May 22, 2011',
    season: 1,
    episode: 13,
    totalViewers: '4.31 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/12',
  },
  {
    id: 38,
    name: '"Topsy"',
    productionCode: '3ASA03',
    airDate: 'March 10, 2013',
    season: 3,
    episode: 16,
    totalViewers: '3.85 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/38',
  },
  {
    id: 27,
    name: '"Tinarannosaurus Wrecks"',
    productionCode: '2ASA14',
    airDate: 'December 2, 2012',
    season: 3,
    episode: 7,
    totalViewers: '3.97 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/27',
  },
  {
    id: 70,
    name: '"Tina and the Real Ghost"',
    productionCode: '4ASA13',
    airDate: 'November 2, 2014',
    season: 5,
    episode: 2,
    totalViewers: '2.891 Million',
    url: 'https://bobsburgers-api.herokuapp.com/episodes/70',
  },
];

export const charData = [
  {
    id: 501,
    name: 'Zeke',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/501.jpg',
    gender: 'Male',
    age: '13-14',
    occupation: 'Student at Wagstaff School',
    relatives: [
      'Unnamed parents',
      'https://bobsburgers-api.herokuapp.com/characters/77',
      'Unnamed 44 year old brother',
      'Unnamed grandparents',
      'Unnamed aunt',
      'https://bobsburgers-api.herokuapp.com/characters/273',
    ],
    firstEpisode: '"The Belchies"',
    voicedBy: 'Bobby Tisdale',
    url: 'https://bobsburgers-api.herokuapp.com/characters/501',
  },
  {
    id: 500,
    name: 'Zander',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/500.jpg',
    gender: 'Male',
    age: '10',
    hairColor: 'Brown',
    occupation: 'Student',
    relatives: ['https://bobsburgers-api.herokuapp.com/characters/465'],
    firstEpisode: '"The Cook, The Steve, The Gayle, & Her Lover"',
    voicedBy: 'H. Jon Benjamin',
    url: 'https://bobsburgers-api.herokuapp.com/characters/500',
  },
  {
    id: 498,
    name: 'Zach',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/498.jpg',
    gender: 'Male',
    hairColor: 'Brown',
    occupation: 'Lifeguard',
    firstEpisode: '"Boywatch"',
    voicedBy: 'Rob Huebel',
    url: 'https://bobsburgers-api.herokuapp.com/characters/498',
  },
  {
    id: 499,
    name: 'Zach',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/499.jpg',
    gender: 'Male',
    hairColor: 'Brown',
    occupation: 'Student at Wagstaff School',
    firstEpisode: '"Boywatch"',
    voicedBy: 'Rob Huebel',
    url: 'https://bobsburgers-api.herokuapp.com/characters/499',
  },
  {
    id: 497,
    name: 'Yuli',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/497.jpg',
    gender: 'Male',
    hairColor: 'Brown',
    occupation: 'Security Guard',
    firstEpisode: '"Burgerboss"',
    voicedBy: 'Robert Smigel',
    url: 'https://bobsburgers-api.herokuapp.com/characters/497',
  },
  {
    id: 496,
    name: 'Yuki Kojima',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/496.jpg',
    gender: 'Female',
    age: '40',
    hairColor: 'Black',
    occupation: 'Former movie actress, Accountant at Deduction Junction',
    relatives: [
      'https://bobsburgers-api.herokuapp.com/characters/442',
      'Unnamed mother',
      'Unnamed son',
    ],
    firstEpisode: '"Hawk & Chick"',
    voicedBy: 'Suzy Nakamura',
    url: 'https://bobsburgers-api.herokuapp.com/characters/496',
  },
  {
    id: 495,
    name: 'Willow',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/495.jpg',
    gender: 'Female',
    hairColor: 'Black',
    relatives: ['https://bobsburgers-api.herokuapp.com/characters/219'],
    firstEpisode: '"Boywatch"',
    voicedBy: 'Natalie Palamides',
    url: 'https://bobsburgers-api.herokuapp.com/characters/495',
  },
  {
    id: 494,
    name: 'Wayne',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/494.jpg',
    gender: 'Male',
    hairColor: 'Brown',
    occupation: 'Student',
    firstEpisode: '"Adventures In Chinchilla-Sitting"',
    voicedBy: 'Andy Richter',
    url: 'https://bobsburgers-api.herokuapp.com/characters/494',
  },
  {
    id: 493,
    name: 'Warren Fitzgerald',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/493.jpg',
    gender: 'Male',
    hairColor: 'Brown',
    occupation: 'Businessman',
    firstEpisode: '"Pro Tiki/Con Tiki"',
    voicedBy: 'Chris Parnell',
    url: 'https://bobsburgers-api.herokuapp.com/characters/493',
  },
  {
    id: 492,
    name: 'Walter Rubens',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/492.jpg',
    gender: 'Male',
    hairColor: 'Brown',
    occupation: 'Goal Setter for The Gold Dragons',
    firstEpisode: '"The Hurt Soccer"',
    voicedBy: 'David Herman',
    url: 'https://bobsburgers-api.herokuapp.com/characters/492',
  },
  {
    id: 491,
    name: 'Vanessa Jackson',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/491.jpg',
    gender: 'Female',
    hairColor: 'Brown',
    occupation: 'Student at Huxley High School',
    firstEpisode: '"Synchronized Swimming"',
    voicedBy: 'John Roberts',
    url: 'https://bobsburgers-api.herokuapp.com/characters/491',
  },
  {
    id: 490,
    name: 'Vanessa',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/490.jpg',
    gender: 'Female',
    hairColor: 'Brown',
    occupation: "Scooper at Moo's Clues Ice Cream",
    firstEpisode: '"The Gene Mile"',
    voicedBy: 'H. Jon Benjamin',
    url: 'https://bobsburgers-api.herokuapp.com/characters/490',
  },
  {
    id: 489,
    name: 'Vance',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/489.jpg',
    gender: 'Male',
    hairColor: 'Brown',
    occupation: 'Station manager at WIXU',
    relatives: ['A son'],
    firstEpisode: '"Long Time Listener, First Time Bob"',
    voicedBy: 'Rob Huebel',
    url: 'https://bobsburgers-api.herokuapp.com/characters/489',
  },
  {
    id: 488,
    name: 'Tyler',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/488.jpg',
    gender: 'Male',
    age: '12',
    hairColor: 'Blonde',
    occupation: 'Student',
    firstEpisode: '"Burgerboss"',
    voicedBy: 'David Herman',
    url: 'https://bobsburgers-api.herokuapp.com/characters/488',
  },
  {
    id: 487,
    name: 'Turd',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/487.jpg',
    gender: 'Male',
    hairColor: 'Light Brown',
    occupation: 'College Student',
    firstEpisode: '"My Big Fat Greek Bob"',
    voicedBy: 'Kurt Braunohler',
    url: 'https://bobsburgers-api.herokuapp.com/characters/487',
  },
  {
    id: 486,
    name: 'Trish',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/486.jpg',
    gender: 'Female',
    hairColor: 'Light Brown',
    occupation: 'Scammer',
    firstEpisode: '"The Runway Club"',
    voicedBy: 'Brooke Dillman',
    url: 'https://bobsburgers-api.herokuapp.com/characters/486',
  },
  {
    id: 485,
    name: 'Trip',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/485.jpg',
    gender: 'Male',
    hairColor: 'Dark blonde',
    occupation: 'Manager at Family Funtime',
    firstEpisode: '"The Taking of Funtime One Two Three"',
    voicedBy: 'Jack McBrayer',
    url: 'https://bobsburgers-api.herokuapp.com/characters/485',
  },
  {
    id: 484,
    name: 'Trina Belson',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/484.jpg',
    gender: 'Female',
    hairColor: 'Unseen',
    occupation: 'Student at Wagstaff School',
    firstEpisode: '"Teen-a Witch"',
    url: 'https://bobsburgers-api.herokuapp.com/characters/484',
  },
  {
    id: 483,
    name: 'Trev',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/483.jpg',
    gender: 'Male',
    age: '20 - 30s',
    hairColor: 'Black',
    occupation: "Bartender at Jimmy Pesto's Pizzeria",
    firstEpisode: '"Sheesh! Cab, Bob?"',
    voicedBy: 'David Herman',
    url: 'https://bobsburgers-api.herokuapp.com/characters/483',
  },
  {
    id: 482,
    name: 'Travis Albright',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/482.jpg',
    gender: 'Male',
    hairColor: 'Blonde',
    occupation: 'Student at Wagstaff School',
    firstEpisode: '"O.T.: The Outside Toilet"',
    url: 'https://bobsburgers-api.herokuapp.com/characters/482',
  },
  {
    id: 481,
    name: 'Tran',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/481.jpg',
    gender: 'Male',
    hairColor: 'Black with Blonde Highlights',
    occupation: "Owner & Operator of Tran's Noodles",
    firstEpisode: '"Moody Foodie"',
    voicedBy: 'Russell Peters',
    url: 'https://bobsburgers-api.herokuapp.com/characters/481',
  },
  {
    id: 480,
    name: 'Tracy Schwartz',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/480.jpg',
    gender: 'Female',
    age: '12',
    hairColor: 'Black',
    occupation: 'Student at Wagstaff School',
    firstEpisode: '"Spaghetti Western and Meatballs"',
    voicedBy: 'Laura Silverman',
    url: 'https://bobsburgers-api.herokuapp.com/characters/480',
  },
  {
    id: 479,
    name: 'Torpedo Jones',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/479.jpg',
    gender: 'Male',
    age: '44',
    hairColor: 'Dirty Blond',
    occupation: 'Baseball player',
    firstEpisode: '"Lobsterfest"',
    voicedBy: 'Robert Ben Garant',
    url: 'https://bobsburgers-api.herokuapp.com/characters/479',
  },
  {
    id: 478,
    name: 'Tommy Jaronda',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/478.jpg',
    gender: 'Male',
    hairColor: 'Brown',
    occupation: 'Health Inspector/Singer',
    firstEpisode: '"Nude Beach"',
    voicedBy: 'Fred Armisen',
    url: 'https://bobsburgers-api.herokuapp.com/characters/478',
  },
  {
    id: 477,
    name: 'Tom Innocenti',
    image: 'https://bobsburgers-api.herokuapp.com/images/characters/477.jpg',
    gender: 'Male',
    age: '40s',
    hairColor: 'Brown',
    occupation: 'Lawyer',
    firstEpisode: '"Sexy Dance Healing"',
    voicedBy: 'Steve Buscemi',
    url: 'https://bobsburgers-api.herokuapp.com/characters/477',
  },
];

export const storData = [
  {
    id: 22,
    name: 'Yes, Wire Hangers!',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/22.jpg',
    season: 2,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/22',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/22',
  },
  {
    id: 216,
    name: "YOU'VE LOST THAT OVEN FEELIN' KITCHEN APPLIANCE REPAIR",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/216.jpg',
    season: 12,
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/216',
  },
  {
    id: 158,
    name: "YOU'RE THE MAN NOW DOG SUITS FOR DOGS",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/158.jpg',
    season: 9,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/159',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/158',
  },
  {
    id: 93,
    name: "YOU'RE MISSING THE POINSETTIA",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/93.jpg',
    season: 6,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/97',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/93',
  },
  {
    id: 188,
    name: "YOU WALKIN' TO ME? PHYSICAL THERAPY",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/188.jpg',
    season: 10,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/188',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/188',
  },
  {
    id: 155,
    name: 'YOU MAKE MY SEAMS COME TRUE TAILORING AND DREAM INTERPRETATION',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/155.jpg',
    season: 9,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/157',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/155',
  },
  {
    id: 124,
    name: 'YOU DO THE METH RECOVERY CLINIC',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/124.jpg',
    season: 7,
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/124',
  },
  {
    id: 117,
    name: "YOU CAN'T HANDLE THE TOOTH DENTAL EXTRACTION",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/117.jpg',
    season: 7,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/116',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/117',
  },
  {
    id: 79,
    name: "YOU CAN'T HANDLE THE RUTH BASEBALL CARDS",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/79.jpg',
    season: 5,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/78',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/79',
  },
  {
    id: 209,
    name: 'YES-TARY POSITIVE NOTARY',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/209.jpg',
    season: 11,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/209',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/209',
  },
  {
    id: 24,
    name: 'YEAR-ROUND HALLOWEEN STORE',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/24.jpg',
    season: 3,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/30',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/24',
  },
  {
    id: 52,
    name: 'YADDA YADDA DADA JEWISH SURREALIST ART GALLERY',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/52.jpg',
    season: 4,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/53',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/52',
  },
  {
    id: 29,
    name: 'Wigs Wigs Wigs! (And Socks)',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/29.jpg',
    season: 3,
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/29',
  },
  {
    id: 203,
    name: 'WREATH OF KHAN THEMED WREATHS',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/203.jpg',
    season: 11,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/203',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/203',
  },
  {
    id: 49,
    name: "WOLF IN SHEEP'S CLOTHING DISCOUNT PET APPAREL",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/49.jpg',
    season: 4,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/47',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/49',
  },
  {
    id: 179,
    name: 'WITH GREAT WHISK COMES GREAT REWARD CULINARY CLASSES',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/179.jpg',
    season: 10,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/178',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/179',
  },
  {
    id: 152,
    name: 'WHOLE LOTTA SHAKER FURNITURE GOING ON',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/152.jpg',
    season: 9,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/154',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/152',
  },
  {
    id: 222,
    name: "WHITE PAINT CAN'T DUMP PAINT RECYCLING CENTER",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/222.jpg',
    season: 12,
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/222',
  },
  {
    id: 173,
    name: 'WHINE COUNTRY MARRIAGE COUNSELING',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/173.jpg',
    season: 10,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/173',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/173',
  },
  {
    id: 201,
    name: "WHERE THE SUN DON'T SHINE TANNING SALON",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/201.jpg',
    season: 11,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/201',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/201',
  },
  {
    id: 211,
    name: 'WHERE THE FILED THINGS ARE FILING CABINETS',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/211.jpg',
    season: 11,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/211',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/211',
  },
  {
    id: 129,
    name: 'WELCOME BACK POTTER SECOND HAND CERAMICS',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/129.jpg',
    season: 7,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/129',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/129',
  },
  {
    id: 164,
    name: 'WEIGHT FOR IT GYM EQUIPMENT',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/164.jpg',
    season: 9,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/164',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/164',
  },
  {
    id: 151,
    name: "WE'VE ALWAYS HAD FERRETS EXOTIC PETS",
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/151.jpg',
    season: 9,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/136',
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/151',
  },
  {
    id: 133,
    name: 'WE LATHER TOGETHER FAMILY SOAPS',
    image: 'https://bobsburgers-api.herokuapp.com/images/storeNextDoor/133.jpg',
    season: 8,
    url: 'https://bobsburgers-api.herokuapp.com/storeNextDoor/133',
  },
];

export const pestData = [
  {
    id: 194,
    name: 'YOU SHOULD GET THAT MOLE LOOKED AT EXTERMINATORS',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/194.jpg',
    season: 11,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/195',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/182',
  },
  {
    id: 54,
    name: 'YOU NEVER CALL, YOU NEVER RAT PEST CONTROL',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/54.jpg',
    season: 4,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/56',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/42',
  },
  {
    id: 106,
    name: 'YOU MOUSE REMEMBER THIS EXTERMINATORS',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/106.jpg',
    season: 6,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/107',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/94',
  },
  {
    id: 225,
    name: 'YOU BETTER NOT MOUSE, YOU BETTER NOT FLIES',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/225.jpg',
    season: 12,
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/213',
  },
  {
    id: 75,
    name: "Wouldn't it be Mice Pest Control",
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/75.jpg',
    season: 5,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/74',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/63',
  },
  {
    id: 19,
    name: 'Wicked Witch of the Pest',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/19.jpg',
    season: 2,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/20',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/7',
  },
  {
    id: 172,
    name: 'WORKING ON MY MITE MOVES PEST CONTROL',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/172.jpg',
    season: 10,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/172',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/160',
  },
  {
    id: 41,
    name: 'WORKING FOR THE SQUEAK-END PEST CONTROL',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/41.jpg',
    season: 3,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/41',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/29',
  },
  {
    id: 28,
    name: 'WILD WILD PEST',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/28.jpg',
    season: 3,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/24',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/16',
  },
  {
    id: 200,
    name: 'WHEN BUGS CRY EXTERMINATORS',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/200.jpg',
    season: 11,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/202',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/188',
  },
  {
    id: 120,
    name: 'WHEN A STRANGER CRAWLS PEST CONTROL',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/120.jpg',
    season: 7,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/115',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/108',
  },
  {
    id: 100,
    name: 'WEAPONS OF MOUSE DESTRUCTION EXTERMINATORS',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/100.jpg',
    season: 6,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/93',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/88',
  },
  {
    id: 212,
    name: "WE'RE GNAT GONNA TAKE IT",
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/212.jpg',
    season: 11,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/213',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/200',
  },
  {
    id: 193,
    name: 'WASPS YOUR PROBLEM? PEST CONTROL',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/193.jpg',
    season: 10,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/193',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/181',
  },
  {
    id: 39,
    name: "VERMIN'S HEAD PEST CONTROL",
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/39.jpg',
    season: 3,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/39',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/27',
  },
  {
    id: 201,
    name: 'VERMIN ON THE VERGE OF A NERVOUS BREAKDOWN PEST CONTROL',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/201.jpg',
    season: 11,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/201',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/189',
  },
  {
    id: 196,
    name: 'VERMIN DOWN THE HOUSE PEST CONTROL',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/196.jpg',
    season: 11,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/196',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/184',
  },
  {
    id: 59,
    name: 'VERM-IN-ENT VACATION Exterminators',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/59.jpg',
    season: 4,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/57',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/47',
  },
  {
    id: 21,
    name: 'The Vermin Surgeon',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/21.jpg',
    season: 2,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/23',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/9',
  },
  {
    id: 55,
    name: 'The Pest of Times and the Worst of Times Exterminators',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/55.jpg',
    season: 4,
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/43',
  },
  {
    id: 46,
    name: 'The GREAT RATSBY Exterminators',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/46.jpg',
    season: 4,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/46',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/34',
  },
  {
    id: 57,
    name: 'Termite-mare ON ELM STREET PEST CONTROL',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/57.jpg',
    season: 4,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/61',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/45',
  },
  {
    id: 123,
    name: 'TWO CRICKETS TO PARADISE EXTERMINATORS',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/123.jpg',
    season: 7,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/122',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/111',
  },
  {
    id: 127,
    name: 'TWO CRICKETS TO PARADISE EXTERMINATORS',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/127.jpg',
    season: 7,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/127',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/115',
  },
  {
    id: 112,
    name: 'TOO BUG TO FAIL EXTERMINATORS',
    image:
      'https://bobsburgers-api.herokuapp.com/images/pestControlTruck/112.jpg',
    season: 7,
    episode: 'https://bobsburgers-api.herokuapp.com/episodes/111',
    url: 'https://bobsburgers-api.herokuapp.com/pestControlTruck/100',
  },
];

export const charDetail = {
  id: 493,
  name: 'Warren Fitzgerald',
  image: 'https://bobsburgers-api.herokuapp.com/images/characters/493.jpg',
  gender: 'Male',
  hairColor: 'Brown',
  occupation: 'Businessman',
  firstEpisode: '"Pro Tiki/Con Tiki"',
  voicedBy: 'Chris Parnell',
  url: 'https://bobsburgers-api.herokuapp.com/characters/493',
};
